default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: rodrigo

development: &development
  <<: *default
  database: cifrao_development

test: &test
  <<: *default
  database: cifrao_test
  min_messages: WARNING

production: &production
  <<: *default
  database: cifrao_production
